/** Códigos FIFA (3 letras) → nombre de la selección en español */
export const TEAM_NAMES_ES: Record<string, string> = {
  MEX: 'México',
  RSA: 'Sudáfrica',
  KOR: 'Corea del Sur',
  CZE: 'Chequia',
  CAN: 'Canadá',
  SUI: 'Suiza',
  QAT: 'Qatar',
  BIH: 'Bosnia y Herzegovina',
  BRA: 'Brasil',
  MAR: 'Marruecos',
  HAI: 'Haití',
  SCO: 'Escocia',
  USA: 'Estados Unidos',
  PAR: 'Paraguay',
  AUS: 'Australia',
  TUR: 'Turquía',
  GER: 'Alemania',
  CUW: 'Curazao',
  CIV: 'Costa de Marfil',
  ECU: 'Ecuador',
  NED: 'Países Bajos',
  JPN: 'Japón',
  TUN: 'Túnez',
  SWE: 'Suecia',
  BEL: 'Bélgica',
  EGY: 'Egipto',
  IRN: 'Irán',
  NZL: 'Nueva Zelanda',
  ESP: 'España',
  CPV: 'Cabo Verde',
  KSA: 'Arabia Saudita',
  URU: 'Uruguay',
  FRA: 'Francia',
  SEN: 'Senegal',
  NOR: 'Noruega',
  IRQ: 'Irak',
  ARG: 'Argentina',
  ALG: 'Argelia',
  AUT: 'Austria',
  JOR: 'Jordania',
  POR: 'Portugal',
  UZB: 'Uzbekistán',
  COL: 'Colombia',
  COD: 'RD Congo',
  ENG: 'Inglaterra',
  CRO: 'Croacia',
  GHA: 'Ghana',
  PAN: 'Panamá',
}
